---
common:
  vars:
    provider_instances:
      service:
        host: "{{ hostvars[groups['provider'] | first].inventory_hostname }}"
        user: usr
        pass: pwd
  hosts:
    host1:
    host2:

consumer:
  vars:
    service_data: "{{ provider_instances }}"
    merge2__1: "{{ service_data }}"  # when using provider_instances directly here would work
  hosts:
    host2:

provider:
  vars:
    merge1: "{{ lookup('community.general.merge_variables', 'merge2__', pattern_type='prefix', groups=['consumer']) }}"
  hosts:
    host1:
